tasks:
  - init: ./gradlew build
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - EditorConfig.EditorConfig
    - vscjava.vscode-java-pack
    - eamodio.gitlens
    - xaver.clang-format
    - mnxn.jvm-bytecode-viewer